export const ADD_CHALLENGE = "ADD_CHALLENGE";
export const TOGGLE_FAVORITE = "TOGGLE_FAVORITE";
export const UPDATE_PROGRESS = "UPDATE_PROGRESS";
export const RESET_PROGRESS = "RESET_PROGRESS";
export const DELETE_CHALLENGE = "DELETE_CHALLENGE";
export const LOAD_FROM_STORAGE = "LOAD_FROM_STORAGE";